### ISSUE TITLE
Bug in module.c / skip_immediate

### ISSUE THREAD

**Issue by eco747** [mcuking/wasmc#4]
Hi, 
there is a small bug in skip_immediate function: a break is missing

```c
case I32Const:
            // I32Const 指令的立即数表示 32 有符号整数（占 4 个字节）
            read_LEB_unsigned(bytes, pos, 32);
HERE>>>>>>>>
        case I64Const:
            // F32Const 指令的立即数表示 64 有符号整数（占 8 个字节）
            read_LEB_unsigned(bytes, pos, 64);
            break;
```

BTW: really good work - thanks for your incredible comments

**Comment by mcuking** [comment]
This commit solves the problem. Thanks very much for your tip!

[fix: 修复 break 关键字缺失问题](https://github.com/mcuking/wasmc/commit/3659231ad445b80843f71407906647095f55dd47)
